<head>
    <title>liq_creative</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- styles -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap-4.0.0-beta.min.css">
    <link rel="stylesheet" type="text/css" href="css/mycss.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <!-- scripts -->
    <script type="text/javascript" src="js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="js/popper-1.12.5.min.js"></script>
    <script type="text/javascript" src="js/bootstrap-4.0.0-beta.min.js"></script>
    <script type="text/javascript" src="js/myjs.js"></script>
</head>